language: dart
sudo: required

addons:
  chrome: stable

jobs:
  include:
    - dart: stable
      name: "SDK: stable"
      script:
        - dartanalyzer .
        - dartfmt -n --set-exit-if-changed .
        - pub run test
    - dart: dev
      name: "SDK: dev"
      script:
        - dartanalyzer .
        - pub run test
