@TestOn('vm')
library test.unit.vm.generated_vm_tests;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/vm -e Environment.vm --no-genHtml`

import './disposable_test.dart' as disposable_test;
import './disposable_transformer/transformations_test.dart' as disposable_transformer_transformations_test;
import './disposable_transformer/transformer_test.dart' as disposable_transformer_transformer_test;
import './func_test.dart' as func_test;
import 'package:test/test.dart';

void main() {
  disposable_test.main();
  disposable_transformer_transformations_test.main();
  disposable_transformer_transformer_test.main();
  func_test.main();
}