@TestOn('vm')
library test.unit.vm.generated_vm_tests;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/vm -e Environment.vm --no-genHtml`

import './func_test.dart' as func_test;
import 'package:test/test.dart';

void main() {
  func_test.main();
}