@TestOn('browser')
library test.unit.browser.generated_browser_tests;

// Generated by `pub run dart_dev gen-test-runner -d test/unit/browser -e Environment.browser --no-genHtml`

import './disposable_test.dart' as disposable_test;
import './invalidation_mixin_test.dart' as invalidation_mixin_test;
import './json_serializable_test.dart' as json_serializable_test;
import 'package:test/test.dart';


void main() {
  disposable_test.main();
  invalidation_mixin_test.main();
  json_serializable_test.main();
}