name: w_common_tools
version: 2.1.2
description: General dev utilities for Dart projects.
homepage: https://www.github.com/Workiva/w_common

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  args: ^2.0.0
  async: ^2.4.0
  colorize: ^3.0.0
  file: ^6.0.0
  glob: ^2.0.0
  meta: ^1.3.0
  package_config: ^2.0.0
  path: ^1.8.0
  sass: ^1.58.1
  source_maps: ^0.10.10
  watcher: ^1.0.0

dev_dependencies:
  build_runner: '>=1.12.0 <3.0.0'
  build_test: ^2.0.0
  build_web_compilers: '>=2.16.5 <4.0.0'
  dependency_validator: ^3.0.0
  mockito: ^5.0.0
  test: ^1.16.2