name: w_common_tools
version: 1.21.8
description: General dev utilities for Dart projects.
homepage: https://www.github.com/Workiva/w_common

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  args: ^1.5.2
  async: ^2.4.0
  colorize: ^2.0.0
  glob: ^1.2.0
  meta: ">=1.1.0 <1.7.0" # Workaround to avoid https://github.com/dart-lang/sdk/issues/46142
  package_config: ^1.1.0
  package_resolver: ^1.0.10
  path: ^1.8.0
  sass: ^1.23.3
  source_maps: ^0.10.10
  watcher: ^0.9.7+12

dev_dependencies:
  build_runner: ^1.7.1
  build_test: ^1.0.0
  build_web_compilers: ^2.5.1
  dependency_validator: ^2.0.0
  file: ^6.0.0
  mockito: ^4.1.1
  test: ^1.16.2

dependency_validator:
  ignore:
    - meta